### ISSUE TITLE
Updating title at index breaking constraints.

### ISSUE THREAD

**Issue by Kaakati** [tapptitude/TTSegmentedControl#11]
I'm trying to update the index title, but when I do, the constraints gets broken. Index 1 moves outside the container.

**Comment by EfraimB** [comment]
Hello Kaakati, can you show me the code on how are you trying to update the titles. Thanks!

**Comment by Kaakati** [comment]
I'm using the Segment as a Stepper tool, inside a CollectionView Cell, updating using closures.

Video: https://youtu.be/eA5dQPHSjrw
Actual Behavior I'm looking for: https://youtu.be/8Sl2Mlm66B4

```swift
lazy var itemCounters : TTSegmentedControl = {
        let segment = TTSegmentedControl()
        segment.allowChangeThumbWidth = false
        segment.allowDrag = true
        segment.hasBounceAnimation = true
        segment.defaultTextFont = UIFont.Fontbook.H2.Normal!
        segment.selectedTextFont  = UIFont.Fontbook.H2.Medium!
        segment.thumbGradientColors = [UIColor.HarrysColors.Green.Light, UIColor.HarrysColors.Green.Light]
        segment.itemTitles = ["-", "0", "+"]
        segment.didSelectItemWith = { (index, title) -> () in
            print("Moved to \(title ?? "")")
            let when = DispatchTime.now() + 0.1 // change 0.2 to desired number of seconds
            if (index == 0) {
                self.minusBtn()
                DispatchQueue.main.asyncAfter(deadline: when) {
                    // Your code with delay
                    segment.selectItemAt(index: 1, animated: true)
                }
            } else if (index == 2) {
                self.plusBtn()
                DispatchQueue.main.asyncAfter(deadline: when) {
                    // Your code with delay
                    segment.selectItemAt(index: 1, animated: true)
                }
            }
        }
        return segment
    }()
```
```swift
func plusBtn() {
        didTapIncrease?()
        itemCounters.changeTitle("1", atIndex: 1)
        print("Increment pressed 👍")
    }
    
func minusBtn() {
        didTapDecrese?()
        itemCounters.changeTitle("0", atIndex: 1)
        print("Decrement pressed 👎")
}
```

**Comment by EfraimB** [comment]
It has been fixed. Thanks for reporting!

**Comment by Kaakati** [comment]
Hello @EfraimB 

I did update the pods, but yet I still face the same problem, any ideas?

#### Update:

Managed to fix the issue using
```swift
cell.itemCounters.setNeedsLayout()
```
